# Change these first
owner: cormorack # Your GitHub username
repo: service-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Interactive Oceans Website
    url: https://interactiveoceans.washington.edu
    maxResponseTime: 5000
    assignees:
      - sdthomas69
  - name: Interactive Oceans Data Portal
    url: https://app.interactiveoceans.washington.edu
    maxResponseTime: 5000
    assignees:
      - lsetiawan
      - dwinasolihin
  - name: Metadata API Service
    url: https://api.ooica.net/metadata/status
    maxResponseTime: 5000
    assignees:
      - lsetiawan
  - name: Data API Service
    url: https://api.ooica.net/data/status
    maxResponseTime: 5000
    assignees:
      - lsetiawan
  - name: Media API Service
    url: https://api.ooica.net/media/
    maxResponseTime: 5000
    assignees:
      - sdthomas69
  - name: Realtime Client API Service
    url: https://api.ooica.net/feed/status
    maxResponseTime: 5000
    assignees:
      - sdthomas69

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /service-status # where "repo" is your repository name
  logoUrl: https://s3.us-west-2.amazonaws.com/media.ooica.net/wp-content/uploads/2019/02/07214108/ooi-rsn-logo.png
  name: CAVA Services Status
  introTitle: "**Welcome** to CAVA Status Page"
  introMessage: This is an uptime monitor and status page, powered entirely by GitHub!
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

commitMessages:
  commitAuthorName: "CAVA Bot"
  commitAuthorEmail: "ooicatest@gmail.com"
