# Change these first
owner: cormorack # Your GitHub username
repo: service-status # Your GitHub repository name

# Add your sites here
sites:
  - name: Production Metadata API Service
    url: https://api.interactiveoceans.washington.edu/metadata/status
    maxResponseTime: 5000

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /service-status # where "repo" is your repository name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CAVA Services Status
  introTitle: "**Welcome** to CAVA Status Page"
  introMessage: This is an uptime monitor and status page, powered entirely by GitHub!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
